# Generated by Django 2.2.3 on 2019-07-24 14:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, unique=True, verbose_name='CompanyName')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etilog.ActivityCategory')),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, unique=True)),
                ('alpha3code', models.CharField(max_length=3, unique=True, verbose_name='alpha-3-code')),
            ],
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, unique=True, verbose_name='MediaType')),
            ],
        ),
        migrations.CreateModel(
            name='SustainabilityCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, unique=True)),
                ('name_long', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SustainabilityTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, unique=True)),
                ('name_long', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, unique=True, verbose_name='ReferenceName')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etilog.Company')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etilog.Country')),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etilog.Media')),
            ],
        ),
        migrations.CreateModel(
            name='ImpactEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date_impact', models.DateField()),
                ('date_published', models.DateField(verbose_name='Date IE published')),
                ('source_url', models.URLField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etilog.Company')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etilog.Country')),
                ('reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etilog.Reference')),
                ('sust_categories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etilog.SustainabilityCategory')),
                ('sust_tags', models.ManyToManyField(blank=True, to='etilog.SustainabilityTag')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etilog.Country'),
        ),
    ]
