# Generated by Django 2.2.3 on 2019-07-25 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etilog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='impactevent',
            old_name='sust_categories',
            new_name='sust_category',
        ),
    ]
