# Generated by Django 2.2.3 on 2019-07-25 14:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('etilog', '0004_sustainabilitycategory_sust_domain'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sustainabilitytag',
            name='name_long',
        ),
        migrations.AlterField(
            model_name='sustainabilitytag',
            name='name',
            field=models.CharField(max_length=35, unique=True),
        ),
    ]
