# Generated by Django 2.2.3 on 2019-07-25 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etilog', '0005_auto_20190725_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
