# Generated by Django 2.2.3 on 2019-07-25 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etilog', '0006_auto_20190725_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sustainabilitycategory',
            name='name',
            field=models.CharField(max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='sustainabilitydomain',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
