# Generated by Django 2.2.3 on 2019-07-26 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etilog', '0007_auto_20190725_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='impactevent',
            name='comment',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
