# Generated by Django 2.2.3 on 2019-08-01 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('etilog', '0009_auto_20190726_1549'),
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('comment', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='impactevent',
            name='date_impact',
            field=models.DateField(blank=True, help_text='optional date of impact', null=True),
        ),
        migrations.AlterField(
            model_name='impactevent',
            name='date_published',
            field=models.DateField(help_text='First time published. If only year is known put 1st of jan',
                                   verbose_name='Date IE published'),
        ),
        migrations.AlterField(
            model_name='impactevent',
            name='summary',
            field=models.CharField(blank=True, help_text='abstract, title or first part of text', max_length=200,
                                   null=True),
        ),
        migrations.AlterField(
            model_name='reference',
            name='country',
            field=models.ForeignKey(blank=True, help_text='optional', null=True,
                                    on_delete=django.db.models.deletion.CASCADE, to='etilog.Country'),
        ),
        migrations.AddField(
            model_name='impactevent',
            name='sources',
            field=models.ManyToManyField(blank=True, to='etilog.Source', verbose_name='further sources'),
        ),
    ]
