# Generated by Django 2.2.3 on 2019-08-01 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etilog', '0010_auto_20190801_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='comment',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
