# Generated by Django 2.2.3 on 2019-08-01 21:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('etilog', '0011_auto_20190801_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='impactevent',
            name='sources',
            field=models.ManyToManyField(blank=True, related_name='impevents', to='etilog.Source',
                                         verbose_name='further sources'),
        ),
    ]
