# Generated by Django 2.2.4 on 2019-08-07 08:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('etilog', '0012_auto_20190801_2340'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='media',
            options={'ordering': ['name'], 'verbose_name': 'medium'},
        ),
        migrations.AddField(
            model_name='source',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='impactevent',
            name='comment',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='impactevent',
            name='summary',
            field=models.CharField(blank=True, help_text='abstract, title or first part of text', max_length=500, null=True),
        ),
    ]
