# Generated by Django 2.2.4 on 2019-08-15 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('etilog', '0013_auto_20190807_1016'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reference',
            old_name='media',
            new_name='mediaform',
        ),
        migrations.AlterField(
            model_name='impactevent',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impevents',
                                    to='etilog.Company'),
        ),
        migrations.AlterField(
            model_name='reference',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='reference', to='etilog.Company'),
        ),
    ]
