# Generated by Django 2.2.4 on 2019-08-20 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('etilog', '0014_auto_20190815_1839'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['name'], 'verbose_name': 'Organisation'},
        ),
        migrations.AddField(
            model_name='company',
            name='owner',
            field=models.ManyToManyField(blank=True, related_name='_company_owner_+', to='etilog.Company'),
        ),
        migrations.AddField(
            model_name='company',
            name='recipient',
            field=models.ManyToManyField(blank=True, related_name='_company_recipient_+', to='etilog.Company'),
        ),
        migrations.AddField(
            model_name='company',
            name='subsidiary',
            field=models.ManyToManyField(blank=True, related_name='_company_subsidiary_+', to='etilog.Company'),
        ),
        migrations.AddField(
            model_name='company',
            name='supplier',
            field=models.ManyToManyField(blank=True, related_name='_company_supplier_+', to='etilog.Company'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='reference',
            name='mediaform',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='etilog.Media'),
        ),
    ]
