# Generated by Django 2.2.4 on 2019-10-03 14:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('etilog', '0019_auto_20190919_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='impactevent',
            name='article_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='impactevent',
            name='date_text',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
