# Generated by Django 2.2.4 on 2019-10-08 09:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('etilog', '0020_auto_20191003_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='impactevent',
            name='article_html',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='impactevent',
            name='article_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
