# Generated by Django 2.2.4 on 2019-10-08 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etilog', '0021_auto_20191008_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='impactevent',
            name='article_title',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
