# Generated by Django 2.2.8 on 2020-01-10 22:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('etilog', '0028_auto_20200110_2341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='owner_old',
        ),
        migrations.RemoveField(
            model_name='company',
            name='recipient_old',
        ),
        migrations.RemoveField(
            model_name='company',
            name='subsidiary_old',
        ),
        migrations.RemoveField(
            model_name='company',
            name='supplier_old',
        ),
    ]
