# Generated by Django 2.2.9 on 2020-05-01 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('etilog', '0031_auto_20200430_2346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='frequentaskedquestions',
            name='image_bottom',
        ),
        migrations.RemoveField(
            model_name='frequentaskedquestions',
            name='image_top',
        ),
        migrations.RemoveField(
            model_name='frequentaskedquestions',
            name='img_bottom_height',
        ),
        migrations.RemoveField(
            model_name='frequentaskedquestions',
            name='img_bottom_width',
        ),
        migrations.RemoveField(
            model_name='frequentaskedquestions',
            name='img_top_height',
        ),
        migrations.RemoveField(
            model_name='frequentaskedquestions',
            name='img_top_width',
        ),
    ]
