# Generated by Django 2.2.9 on 2020-05-04 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('etilog', '0032_auto_20200501_1053'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelatedQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('from_questions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_questions', to='etilog.FrequentAskedQuestions', verbose_name='master_question')),
                ('to_questions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_questions', to='etilog.FrequentAskedQuestions', verbose_name='related_question')),
            ],
        ),
        migrations.AddField(
            model_name='frequentaskedquestions',
            name='related_question',
            field=models.ManyToManyField(blank=True, related_name='to_master_question', through='etilog.RelatedQuestion', to='etilog.FrequentAskedQuestions'),
        ),
    ]
