# Generated by Django 2.2.9 on 2020-10-26 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etilog', '0034_auto_20200820_1746'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Local Name')),
                ('code_639_1', models.CharField(max_length=2, unique=True, verbose_name='ISO 639-1')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
