# Generated by Django 2.2.9 on 2020-10-26 10:11

from django.db import migrations


def add_languages(apps, schema_editor):
    # We can't import the Language model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Language = apps.get_model('etilog', 'Language')
    Language.objects.update_or_create(name='English', code_639_1='en')


class Migration(migrations.Migration):

    dependencies = [
        ('etilog', '0035_language'),
    ]

    operations = [
        migrations.RunPython(add_languages),
    ]
