# Generated by Django 2.2.9 on 2020-10-26 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etilog', '0036_auto_20201026_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='impactevent',
            name='language',
            field=models.ForeignKey(default=1, on_delete=models.SET(1), to='etilog.Language'),
        ),
    ]
