# Generated by Django 2.2.9 on 2020-10-29 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etilog', '0037_impactevent_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='impactevent',
            name='article_byline',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
