# Generated by Django 2.2.9 on 2020-10-12 13:38

from django.db import migrations


def add_profil(apps, schema_editor):
    Profile = apps.get_model('usermgmt', 'Profile')
    User = apps.get_model('auth', 'User')
    for user in User.objects.all():
        Profile.objects.create(user=user)


class Migration(migrations.Migration):

    dependencies = [
        ('usermgmt', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_profil),
    ]
