# Generated by Django 2.2.9 on 2020-11-19 16:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('etilog', '0039_auto_20201109_1035'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usermgmt', '0003_auto_20201012_1644'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relevance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('relevance_point', models.SmallIntegerField()),
                ('impact_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='etilog.ImpactEvent')),
                ('reference', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='etilog.Reference')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
